#include "./alta/index.h"
#include "./buscar/index.h"
#include "./funcionesFILE/index.h"
#include "./listar/index.h"
#include "./modificar/index.h"
#include "./preguntarContinuar/index.h"
#include "./printPropiedad/index.h"
#include "./baja-logica/index.h"
#include "./baja-fisica/index.h"

